#!/usr/bin/env bash

cdmkdir(){
    mkdir -p $1 && cd $1
}

dobis(){
    local title=""
    local draft=""
    local other_args=()

    while [[ $# -gt 0 ]]; do
        case "$1" in
            -d|--draft)
                draft="--draft"
                ;;
            *)
                if [[ -z "$title" ]]; then
                    title="$1"
                else
                    other_args+=("$1");
                fi
                ;;
        esac
        shift
    done
    
    if [[ ${#other_args} -gt 0 ]]; then
        echo "Unknown args ${other_args[@]}"
        return
    fi


    if [[ ! -z $draft ]]; then
        gh pr create --assignee "@me" --title "$title" --fill --draft
    else
        gh pr create --assignee "@me" --title "$title" --fill
    fi
}